name: Pull Request Code Reviews

# Controls when the workflow will run
on:
  pull_request:
    types: [opened]

jobs:
  - name: slack-send
    uses: slackapi/slack-github-action@v1.22.0
    with:
    # For posting a rich message using Block Kit
    payload: |
      {
        "text": "Hi",
        "blocks": [
          {
            "type": "section",
            "text": {
              "type": "plain_text",
              "text": "This is a plain text section block.",
              "emoji": true
            }
          }
        ]
      }
    env:
      SLACK_WEBHOOK_URL:  ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

